#!/usr/bin/env node
const http=require('http'),fs=require('fs'),path=require('path'),os=require('os');
const{spawn}=require('child_process');
const PORT=parseInt(process.env.MONSE_PROXY_PORT||'8765',10);
const BACKEND='http://129.159.45.114';
const CFG=path.join(os.homedir(),'.monse','config.json');
const PID=path.join(os.homedir(),'.monse','proxy.pid');
const LOG=path.join(os.homedir(),'.monse','proxy.log');
const SRV=path.join(os.homedir(),'.monse','proxy-server','server.js');
const G='\x1b[32m',R='\x1b[31m',Y='\x1b[33m',B='\x1b[1m',X='\x1b[0m';
const ok=s=>G+'[OK] '+X+s,er=s=>R+'[ERR] '+X+s,wn=s=>Y+'[WARN] '+X+s;
function lcfg(){try{return JSON.parse(fs.readFileSync(CFG,'utf8'));}catch{return{};}}
function scfg(d){fs.mkdirSync(path.dirname(CFG),{recursive:true});fs.writeFileSync(CFG,JSON.stringify(Object.assign(lcfg(),d),null,2));}
function get(p,t){return new Promise((res,rej)=>{const r=http.get('http://localhost:'+PORT+p,{timeout:t||3000},s=>{let d='';s.on('data',c=>d+=c);s.on('end',()=>{try{res(JSON.parse(d));}catch{res({});}});});r.on('error',rej);r.on('timeout',()=>{r.destroy();rej(new Error('timeout'));});});}
async function up(){try{const r=await get('/health',1500);return r.status==='healthy';}catch{return false;}}
async function cmdStatus(){const r=await up();console.log(r?ok('Proxy running -> localhost:'+PORT):er('Proxy not running. Run: monse on'));if(!r)return;const[h,sv]=await Promise.all([get('/health'),get('/savings')]);console.log('Backend: '+h.backend+' Uptime: '+h.uptime+'s');console.log('Requests: '+sv.session_requests+' Cache: '+sv.session_cache_hit_rate);console.log(G+'Saved: $'+parseFloat(sv.session_saved_usd||0).toFixed(4)+X);}
async function cmdSavings(){if(!await up()){console.log(er('Not running'));return;}const sv=await get('/savings');const saved=parseFloat(sv.session_saved_usd||0);const cost=parseFloat(sv.session_cost_usd||0);const orig=saved+cost;const pct=orig>0?((saved/orig)*100).toFixed(1):'0.0';const ann=saved*(365*24*3600/Math.max(sv.runtime_seconds||1,1));console.log('Requests: '+sv.session_requests+' Cache: '+sv.session_cache_hit_rate);console.log('Without Monse: $'+orig.toFixed(6)+' With Monse: $'+cost.toFixed(6));console.log(G+B+'Saved: $'+saved.toFixed(6)+' ('+pct+'%)'+X);console.log(G+'Annualised: $'+ann.toFixed(2)+'/yr'+X);}
async function cmdDoctor(){let pass=0,total=0;async function chk(label,fn){total++;try{const r=await fn();if(r.ok){console.log(ok(label+(r.note?' '+r.note:'')));pass++;}else{console.log(er(label+(r.note?' -> '+r.note:'')));}}catch(e){console.log(er(label+' -> '+e.message));}}await chk('Node.js>=16',async()=>({ok:parseInt(process.versions.node,10)>=16,note:'v'+process.versions.node}));await chk('Proxy installed',async()=>({ok:fs.existsSync(SRV)}));await chk('Proxy running',async()=>{const r=await up();return{ok:r,note:r?'ok':'run: monse on'};});try{const resp=await new Promise((res,rej)=>{const r=http.get(BACKEND+'/health',{timeout:5000},s=>{let d='';s.on('data',c=>d+=c);s.on('end',()=>res(s.statusCode));});r.on('error',rej);});await chk('Backend reachable',async()=>({ok:resp===200,note:BACKEND}));}catch(e){await chk('Backend reachable',async()=>({ok:false,note:e.message}));}const key=(lcfg().apiKey||process.env.ANTHROPIC_API_KEY||'');await chk('API key',async()=>({ok:key.startsWith('tok_monse_'),note:key.startsWith('tok_monse_')?'...'+key.slice(-6):'run: monse set-key tok_monse_xxx'}));await chk('ANTHROPIC_BASE_URL',async()=>({ok:(process.env.ANTHROPIC_BASE_URL||'').includes('localhost:'+PORT),note:process.env.ANTHROPIC_BASE_URL||'not set'}));await chk('OPENAI_BASE_URL',async()=>({ok:(process.env.OPENAI_BASE_URL||'').includes('localhost:'+PORT),note:process.env.OPENAI_BASE_URL||'not set'}));console.log(pass+'/'+total+' checks passed');}
async function cmdOn(){if(await up()){console.log(wn('Already running'));return;}if(!fs.existsSync(SRV)){console.log(er('Not installed'));process.exit(1);}fs.mkdirSync(path.dirname(LOG),{recursive:true});const c=spawn('node',[SRV],{detached:true,stdio:['ignore',fs.openSync(LOG,'a'),fs.openSync(LOG,'a')],env:Object.assign({},process.env,{MONSE_PROXY_PORT:String(PORT),MONSE_BACKEND_URL:BACKEND})});c.unref();fs.writeFileSync(PID,String(c.pid));for(let i=0;i<10;i++){await new Promise(r=>setTimeout(r,400));if(await up()){console.log(ok('Proxy started (PID '+c.pid+') -> localhost:'+PORT));return;}}console.log(wn('Proxy started'));}
function cmdOff(){if(!fs.existsSync(PID)){console.log(wn('No PID file'));return;}const pid=parseInt(fs.readFileSync(PID,'utf8').trim(),10);try{process.kill(pid,'SIGTERM');fs.unlinkSync(PID);console.log(ok('Stopped (PID '+pid+')'));}catch(e){console.log(er(e.message));}}
function cmdLogs(){if(!fs.existsSync(LOG)){console.log(wn('No logs yet'));return;}spawn('tail',['-f',LOG],{stdio:'inherit'}).on('exit',()=>process.exit(0));}
function cmdSetKey(key){if(!key||!key.startsWith('tok_monse_')){console.log(er('Usage: monse set-key tok_monse_xxx'));process.exit(1);}scfg({apiKey:key});console.log(ok('Key saved'));console.log('  export ANTHROPIC_API_KEY='+key);console.log('  export ANTHROPIC_BASE_URL=http://localhost:'+PORT);console.log('  export OPENAI_API_KEY='+key);console.log('  export OPENAI_BASE_URL=http://localhost:'+PORT+'/v1');}
function cmdConfig(){const c=lcfg();console.log('Key: '+(c.apiKey?'...'+c.apiKey.slice(-6):'not set')+' Port: '+PORT+' Backend: '+BACKEND);}
function cmdHelp(){console.log('monse -- Monse.ai CLI\nCommands: on off status savings doctor logs config set-key');}
(async()=>{const[,,cmd,...args]=process.argv;switch(cmd){case'status':await cmdStatus();break;case'savings':await cmdSavings();break;case'doctor':await cmdDoctor();break;case'on':case'start':await cmdOn();break;case'off':case'stop':cmdOff();break;case'logs':cmdLogs();break;case'config':cmdConfig();break;case'set-key':cmdSetKey(args[0]);break;case'help':case'--help':case undefined:cmdHelp();break;default:console.log('Unknown: '+cmd);process.exit(1);}})();
